Setup tailscale connection
metal-stack/metal-images pull request #141
Opened 2022-07-13 12:25 UTC by GrigoriyMikhalkin

2022-07-14 08:44 UTC, majst01 commented
@GrigoriyMikhalkin #142 is merged

2022-07-20 05:21 UTC, majst01 commented on debian/docker-make.debian.yaml
> +      - FRR_VERSION_DETAIL=8.3-0~deb10u1
please do not update frr with this PR, this must be done in a separate one

2022-07-27 08:50 UTC, GrigoriyMikhalkin commented
@majst01 Firewall image need to have `iptables` binary for `tailscaled` to work. There's [ongoing work to migrate `tailscaled` from using `iptables` to `netlink`](https://github.com/tailscale/tailscale/issues/391), but at the moment it still relies on it.

2022-07-27 08:52 UTC, majst01 commented
> @majst01 Firewall image need to have `iptables` binary for `tailscaled` to work. There's [ongoing work to migrate `tailscaled` from using `iptables` to `netlink`](https://github.com/tailscale/tailscale/issues/391), but at the moment it still relies on it.

This is bad, iptables will interfere with nftables i think, but for the start we should at least try with both installed.

2022-09-09 11:14 UTC, majst01 requested changes

2022-09-09 11:14 UTC, majst01 commented on firewall/Dockerfile
> +ARG TAILSCALE_VERSION=v1.28.0
1.30.1

2022-09-09 11:14 UTC, majst01 commented on firewall/Dockerfile
> + && apt install --yes iptables
just dont remote iptables, add it to the list of packages to be installed and remove the apt-get remove iptables step

2022-09-16 14:20 UTC, GrigoriyMikhalkin commented
@majst01 Update tiptables installation. Tested with mini-lab, it worked. So at least in mini-lab environment it's required to reinstall `iptables`.

2022-09-16 14:33 UTC, majst01 commented
> @majst01 Update `iptables` installation. Tested with mini-lab, it worked. So at least in mini-lab environment it's required to reinstall `iptables`.

Strange but good to know. Dont understand, can you please add a comment alongside these lines for later reference, otherwise someone will simply "optimize" this particular part.

2022-09-23 12:09 UTC, majst01 approved these changes

2022-09-23 12:09 UTC, merged